name: aidrugdiscovery
version: git
summary: toolkit
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

parts:
  offlineimap:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
      - python-pip
    plugin: conda
    
    conda-packages:
      - rdkit
      - PySimpleGUI
      - IPython
      - matplotlib
      - sklearn
      - pytorch
      - tables
      - keras
      - tensorflow
      - nbformat
      - nbconvert
  


apps:
  offlineimap:
    command: bin/aidrugdiscovery
