name: aidrugdiscovery
version: "1"
summary: chemoinformatics toolkit
description: chemoinformatics toolkit
base: core18
grade: stable
confinement: strict
parts:
  
      
  mainpart:
    plugin: python
    python-packages: 
      -IPython
      -PySimpleGUI


  aidrugdiscovery:
    plugin: dump
    source: https://github.com/patrickchirdon/AIdrugdiscovery.git
    source-type: git
    override-build: |
      ./bmetoolkit
      snapcraftctl build
  
  
  
  
  
  

    
