name: aidrugdiscovery
version: git
summary: toolkit
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

parts:
  offlineimap:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
      - python-PySimpleGUI
      -python-IPython
      -python-matplotlib
      -python-sklearn
      -python-torch
      -python-tables
      -python-keras
      -python-tensorflow
      -python-nbformat
      -python-nbconvert

apps:
  offlineimap:
    command: bin/offlineimap
