name: aidrugdiscovery
version: "2.10"
summary: GNU Hello, the "hello world" snap
description: GNU Hello prints a friendly greeting.
grade: stable
confinement: strict

apps:
  rdkit:
    command: rdkit

parts:
  gnu-hello:
    plugin: autotools
    source: https://github.com/rdkit/rdkit.git
    
    
