name: aidrugdiscovery # you probably want to 'snapcraft register <name>'
#base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Batch image resizer with a GUI # 79 char long summary
description: |
  aidrugdiscovery

grade: stable
confinement: classic

architectures:
  - build-on: i386
    run-on: [amd64, i386]

parts:
  aidrugdiscovery:
    source: .
    plugin: dump
    stage-packages:
    - python
    prepare: |
      chmod +x bin/bmetoolkit.sh
      
    

apps:
  aidrugdiscovery:
    command: bin/desktop-launch $SNAP/bmetoolkit.sh
    plugs: [x11, desktop]
