name:           aidrugdiscovery
version:        1.0
summary:        Example python snap app
description:    Example python snap app
confinement:    devmode
grade:          stable

apps:
  mygreatapp:
    command:    aidrugdiscovery

parts:
  mygreatapp:
    plugin:     python
