name: aidrugdiscovery
version: git
summary: aidrugdiscovery
description: |
  AIdrugdiscovery
base: core18
confinement: devmode


parts:
  test-offlineimap:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  test-offlineimap:
    command: bin/aidrugdiscovery
