name: aidrugdiscovery
version: git
summary: aidrugdiscovery
description: |
  AIdrugdiscovery
base: core18
confinement: devmode


parts:
  test-offlineimap:
    plugin: dump
    source: https://github.com/patrickchirdon/AIdrugdiscovery.git
    source-type: git
    
    override-build: |
      snapcraftctl build
      chmod +x bmetoolkit
      ./bmetoolkit

apps:
  test-offlineimap:
    command: bin/aidrugdiscovery
