name: aidrugdiscovery
version: "1"
summary: chemoinformatics toolkit
description: chemoinformatics toolkit
base: core18
grade: stable
confinement: strict
parts:
  aidrugdiscovery:
  plugin: dump
  source: https://github.com/patrickchirdon/AIdrugdiscovery.git
  source-type: git
  override-build: |
    ./bmetoolkit
    ./bmetoolkit1.0.sh
    snapcraftctl build
  
  
  
  
  
  

    
