name: aidrugdiscovery
version: "1"
summary: toolkit
description: chemoinformatics toolkit
grade: stable
confinement: strict

apps:
  bmetoolkit:
    command: bmetoolkit

parts:
  gnu-hello:
    plugin: autotools
    source: https://github.com/rdkit/rdkit.git
    source: https://github.com/PySimpleGUI/PySimpleGUI.git
    source: https://github.com/scikit-learn/scikit-learn.git

    conda-packages:
     
     
      - IPython
      - matplotlib
      
      - pytorch
      - tables
      - keras
      - tensorflow
      - nbformat
      - nbconvert
      - runipy
  


apps:
  offlineimap:
    command: bin/aidrugdiscovery
