name: aidrugdiscovery
version: git
summary: toolkit
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

parts:
  
  offlineimap:
    
    source: https://github.com/rdkit/rdkit.git
    source: https://github.com/PySimpleGUI/PySimpleGUI.git
    source: https://github.com/scikit-learn/scikit-learn.git
    plugin: conda
    
    conda-packages:
     
     
      - IPython
      - matplotlib
      
      - pytorch
      - tables
      - keras
      - tensorflow
      - nbformat
      - nbconvert
      - runipy
  


apps:
  offlineimap:
    command: bin/aidrugdiscovery
