name: aidrugdiscovery
version: 1.0
summary: Cross-Platform Benchmark
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

parts:
  geekbench4:
    plugin: dump
    source: https://github.com/patrickchirdon/AIdrugdiscovery.git

apps:
  aidrugdiscovery:
    command: aidrugdiscovery
