name: aidrugdiscovery
version: 1.0
summary: Cross-Platform Benchmark
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

apps:
  foo:
    command: sh $SNAP/bmetoolkit

parts:
  foo:
    source: .
    plugin: dump
    organize:
            bmetoolkit: bmetoolkit
