name: aidrugdiscovery
version: git
summary: toolkit
description: |
  chemoinformatics toolkit

confinement: devmode
base: core18

parts:
  offlineimap:
   
    plugin: conda
    
    conda-packages:
      - rdkit
      - PySimpleGUI
      - IPython
      - matplotlib
      - sklearn
      - pytorch
      - tables
      - keras
      - tensorflow
      - nbformat
      - nbconvert
      - runipy
  


apps:
  offlineimap:
    command: bin/aidrugdiscovery
